### ISSUE TITLE
update the sorting technique in a new language 

### ISSUE THREAD

**Issue by ishitaojha** [Grace-Hephzibah/Sort#1]

**Comment by Grace-Hephzibah** [comment]
Do you want to work on this issue ?

**Comment by ishitaojha** [comment]
Yeah Sure I can add different sorting techniques using Java.
I have made a self repo for the same too but I thought contributing would
be fun.😃

**Comment by Grace-Hephzibah** [comment]
Sure. Go Ahead.

**Comment by Grace-Hephzibah** [comment]
Assigning this issue to you 
(28 days time)

**Comment by ishitaojha** [comment]
Okay, thank you.
